apiVersion: apps/v1
kind: Deployment
metadata:
  name: amclab-deployment
  labels:
    app: web-app
  namespace: ejaka
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: ejakah/amc-wintersemester:latest
        ports:
        - containerPort: 80
